"""empty message

Revision ID: af06cc88f8f4
Revises: 
Create Date: 2021-12-18 20:46:13.967683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af06cc88f8f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lang_tag", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_name",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("lang_id", sa.Integer(), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["lang_id"],
            ["language.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("lang_id", sa.Integer(), nullable=True),
        sa.Column("tag_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["lang_id"],
            ["language.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_tag")
    op.drop_table("company_name")
    op.drop_table("language")
    op.drop_table("company")
    # ### end Alembic commands ###
